import React from 'react'
import { TabGroup } from '@statikly/funk'

export default function MyTabs() {
    return (
        <div className="w-full flex flex-col">
            <TabGroup numTabs={5} direction={TabGroup.direction.HORIZONTAL}>
                <TabGroup.TabList className="text-sm font-bold">
                    <TabGroup.Tab
                        index={0}
                        className="h-10 px-3 transition-colors duration-300"
                        activeClassName="border-gray-300 border-2 border-b-stone-50 border-b-2 hover:text-blue-800"
                        inactiveClassName="text-gray-400 hover:text-blue-800 border-b"
                    >
                        ABOUT
                    </TabGroup.Tab>
                    <TabGroup.Tab
                        style={{ backgournd: "#000" }}
                        index={1}
                        className="h-10 px-3 transition-colors duration-300"
                        activeClassName="border-gray-300 border-2 border-b-stone-50 border-b-2 hover:text-blue-800"
                        inactiveClassName="text-gray-400 hover:text-blue-800 border-b"
                    >
                        FEATURES
                    </TabGroup.Tab>
                    <TabGroup.Tab
                        index={2}
                        className="h-10 px-3 transition-colors duration-300"
                        activeClassName="border-gray-300 border-2 border-b-white hover:text-blue-800"
                        inactiveClassName="text-gray-400 hover:text-blue-800 border-b"
                    >
                        APPLICATION
                    </TabGroup.Tab>
                    <TabGroup.Tab
                        index={3}
                        className="h-10 px-3 transition-colors duration-300"
                        activeClassName="border-gray-300 border-2 border-b-white hover:text-blue-800"
                        inactiveClassName="text-gray-400 hover:text-blue-800 border-b"
                    >
                        DOWNLOADS
                    </TabGroup.Tab>
                    <TabGroup.Tab
                        index={4}
                        className="h-10 px-3 transition-colors duration-300"
                        activeClassName="border-gray-300 border-2 border-b-white hover:text-blue-800"
                        inactiveClassName="text-gray-400 hover:text-blue-800 border-b"
                    >
                        VIDEOS
                    </TabGroup.Tab>

                </TabGroup.TabList>
                <TabGroup.TabPanel
                    index={0}
                    className="pt-10 transition-all transform h-64 text-gray-500 text-lg h-auto"
                    activeClassName="opacity-100 duration-500"
                    inactiveClassName="absolute opacity-0 -translate-x-2"
                >
                    What is Authenticate?
                    <br /><br />Amped Authenticate is a software package for forensic image authentication and tamper detection on digital photos. Authenticate provides a suite of different tools to determine whether an image is an unaltered original, an original generated by a specific device, or the result of a manipulation with a photo editing software and thus may not be accepted as evidence. Current products and processes are focused on one or a relative few scientific tools. Authenticate puts the power of multiple tests, procedures, and reporting in one package to improve the user’s ability to detect tampered images or determine originality.
                    <br /><br />Why is Authenticate needed?
                    <br /><br />Understanding if an image is an original or the result of manipulation is not as easy task. Until now only few world-recognized experts where able to determine if an image used as evidence in court was effectively an original or if someone has tampered with it and thus it was not acceptable as evidence or as alibi. Experts have previously had to do this with self-made tools and very specialized scientific techniques. Today, the number of times that experts are asked to provide some insight on the authenticity of a photo are increasing at a drastic rate. The courts and savvy defense attorneys/prosecutors have begun to understand how easy is to manipulate a digital picture.
                    <br /><br />This is why Authenticate is needed today
                    <br /><br />With Authenticate, Amped finally empowers law enforcement experts and forensic labs with a tool able to discover any tampering that has been done on an image and verify if a digital photography has been generated by a specific device. Our camera ballistics determines that a specific device – and not just the make or model – was used to generate a specific picture. This tool scientifically determines the origin of a photo, not just a comparison of various patterns in a database. Amped has integrated in a single and easy to use package forensically accepted techniques that were previously available with custom tools on to top notch researchers. But it has gone farther than that: before Authenticate the main difficult of the analysis has been to put together very heterogeneous results coming from different kind of analysis, sometime in contrast between them, which left the expert a very heavy duty of logical analysis between the cause-effect of different issues.
                </TabGroup.TabPanel>
                <TabGroup.TabPanel
                    index={2}
                    className="pt-10 transition-all transform flex flex-col h-auto"
                    activeClassName="opacity-100 duration-500 translate-x-0"
                    inactiveClassName="absolute opacity-0 -translate-x-2"
                >
                    <p className="text-lg text-gray-500">
                        >>Forensics
                        <br /><br />>>Video surveillance intelligence agencies
                        <br /><br />>>Biometrics
                        <br /><br />>>Research
                    </p>
                </TabGroup.TabPanel>
                <TabGroup.TabPanel
                    index={1}
                    className="pt-10 transition-all transform h-64 h-auto"
                    activeClassName="opacity-100 duration-500 translate-x-0"
                    inactiveClassName="absolute opacity-0 -translate-x-2"
                >
                    <span className="text-lg text-gray-500">
                        >>Supported Formats
                        <br />Support for any standard image format (jpeg, tiff, bmp, png…) and raw format from digital cameras.
                        <br /><br />
                        >>Available filters
                        <br />More than 20 different analysis filters, with user customizable configuration and optional post processing parameters (levels, scale to enhance the displayed image).
                        <br /><br />
                        >>Image Display
                        <br />Embedded viewer with multiple image comparison and synchronization.
                        <br /><br />
                        >>Comparison Support
                        <br />Most of the filters allow comparison of the results between two images.
                        <br /><br />
                        >>Output Image Export Options
                        <br />Support for any standard image format (jpeg, tiff, bmp, png…).
                        <br /><br />
                        >>Output Data Export Options
                        <br />Export analysis output as plain text, HTML, or TSV.
                        <br /><br />
                        >>Cached Processing
                        <br />Filter results are saved in a cache folder for speedy subsequent analysis.
                        <br /><br />
                        >>Batch Processing
                        <br />Automatically apply all filters to all images in a folder.
                        <br /><br />
                        >>Batch File Format Analysis
                        <br />Quick automatic analysis of the format of all images in a folder to find suspicious files (triage).
                        <br /><br />
                        >>Batch File Format Comparison
                        <br />Quick automatic comparison of the format of all files in a folder with the analyzed image.
                        <br /><br />
                        >>Batch JPEG Comparison
                        <br />Quick automatic comparison of the quantization tables of all files in a folder with the analyzed image.
                        <br /><br />
                        >>Excel Integration
                        <br />Export of multiple file analysis table directly to Microsoft Excel spreadsheets for further processing.
                        <br /><br />
                        >>Google Maps Integration
                        <br />Display image location in Google Maps.
                        <br /><br />
                        >>Google Images Integration
                        <br />Search for similar images and images from a certain specific camera on Google Images. Supports advanced image features filtering.
                        <br /><br />
                        >>Flickr Integration
                        <br />Search for images from a certain camera on Flickr. Supports advanced image features filtering.
                        <br /><br />
                        >>TinEye Integration
                        <br />Search for similar images on TinEye.
                        <br /><br />
                        >>Extraction Of Embedded JPGs
                        <br />Extract JPEG images embedded in any file type (PDF, PPT, DOC, disk image…) for questioned document authentication support.
                        <br /><br />
                        >>Samples
                        <br />A rich collection of samples.
                        <br /><br />
                        >>Supported Platforms
                        <br />Windows XP, Vista, 7, 8. 32 bit and 64 bit version in a single installer.
                        <br /><br />
                        >>Licensing Mode
                        <br />Standalone software. Protected by a USB dongle, doesn’t require any online activation.
                    </span>
                </TabGroup.TabPanel>
                <TabGroup.TabPanel
                    index={3}
                    className="pt-10 transition-all transform h-64 h-auto"
                    activeClassName="opacity-100 duration-500 translate-x-0"
                    inactiveClassName="absolute opacity-0 -translate-x-2"
                >
                    <p className="text-lg text-gray-500">Please contact us and request for additional information.</p>
                </TabGroup.TabPanel>
                <TabGroup.TabPanel
                    index={4}
                    className="pt-10 transition-all transform h-64 h-auto"
                    activeClassName="opacity-100 duration-500 translate-x-0"
                    inactiveClassName="absolute opacity-0 -translate-x-2"
                >
                    <p className="text-lg text-gray-500">Please contact us and request for additional information.</p>
                </TabGroup.TabPanel>
            </TabGroup>
        </div>
    )
}